### ISSUE TITLE
Add custom configuration check

### ISSUE THREAD

**Issue by alimac** [alimac/err-request-tracker#3]
```
12:07:24 ERROR    errbot.plugin_manager     Error loading RT
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/errbot/plugin_manager.py", line 390, in activate_plugin
    self.activate_plugin_with_version_check(name, self.get_plugin_configuration(name))
  File "/usr/lib/python2.7/site-packages/errbot/plugin_manager.py", line 203, in activate_plugin_with_version_check
    raise PluginConfigurationException(unicode(e))
PluginConfigurationException: changeme [<type 'str'>] is not the same type as foo [<type 'unicode'>]
```

**Comment by alimac** [comment]
Current workaround is

```
    def check_configuration(self, configuration):
        pass
```

But we should add configuration checks here

**Comment by alimac** [comment]
Custom configuration check is in. I noticed that giving it bad config triggers an exception, but doesn't output any message to the user. For example:

```
!plugin config RT {}
Plugin configuration done.
```

Expected behavior:

```
!plugin config RT {}
RT failed to start : missing config value: REST_URL
```

I am not sure how to make the exception be shown in response.

**Comment by alimac** [comment]
It looks like this might be "works as designed" -- if configuration check fails, the plugin is disabled. So to test the check, we can call `!plugin activate RT` to output the error, as done in b650843b75fa3a5c00200630b26e, 3751b642e1c232393b2fc84780067f, and 9eaa02ebec7154f17c5b7685505264a8.
